bandsite/config/routes.rb
Bandsite::Application.routes.draw do

  # mount Rich::Engine => '/rich', :as => 'rich'

  devise_for :users
  devise_for :fans


  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root to: "home#home"
  
  resources :posts do 
    get 'page/:page', action: :index, on: :collection
    get :photo, on: :member
    resources :post_comments
  end

  resources :tracks do
    get :song, on: :member
    resources :track_comments
  end

  resources :albums do
    get :photo, on: :member
  end

  resources :fans do
    resources :fan_comments
  end

  resources :friends do
    get :photo, on: :member
  end

  resources :reviews do
    get :photo, on: :member
    resources :review_comments
  end

  get 'reviews', to: 'reviews#index'
  get 'gigs', to: 'gigs#index'
  get 'friends', to: 'friends#index'
  get 'treasure_chest', to: 'fans#index'
  get 'contacts', to: 'contacts#index'
  get 'photogallery', to: 'photogallerys#index'

  resources :comments
end

bandsite/app/views/layouts/_menu.html.erb
<div class='menu'>
 <div>
    <h3><%= link_to 'Home', root_path %></h3>
  </div>
   <div>
    <h3><%= link_to 'Captains Blog', posts_path %></h3>
  </div>
  <div>
    <h3><%= link_to 'My Music', albums_path %></h3>
  </div>
 <div>
    <h3><%= link_to 'Photo Gallery', photogallery_path %></h3>
  </div>
  <div>
    <h3><%= link_to 'See Me Play', gigs_path %></h3>
  </div>
 <div>
    <h3><%= link_to 'Meet My Friends', friends_path %></h3>
  </div>
 <div>
    <h3><%= link_to 'Treasure Chest', treasure_chest_path %></h3>
  </div>
  <div>
    <h3><%= link_to 'What They Say...', reviews_path %></h3>
  </div>
 <div>
    <h3><%= link_to 'Contact Me', contacts_path %></h3>
 </div>

 <%= render 'layouts/social' %>
</div>
<br>
<br>

bandsite/app/views/layouts/_social.html.erb
<div class="social-partial">
  <ul class="social">
    <li class="facebook">
      <a href="https://www.facebook.com/sharer/sharer.php?u=<%= request.url %>" title="Share on Facebook"><img src="/assets/facebook.png"></a>
    </li>
    <li class="twitter">
      <a href="https://twitter.com/intent/tweet?text=<%= request.url %>" title="Share on Twitter"><img src="/assets/twitter.png"></a>
    </li>
    <li class="googleplus">
      <a href="https://plus.google.com/share?url=<%= request.url %>" title="Share on Google Plus"><img src="/assets/google+.png"></a>
    </li>
  </ul>
</div>

bandsite/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gwyneth Herbert</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
 
  <link href='/assets/compositebwunderlay.ico' rel='icon' type='image/x-icon' />
  <link href='http://fonts.googleapis.com/css?family=IM+Fell+DW+Pica' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Lora' rel='stylesheet' type='text/css'>
</head>
<body>
<div class="header-text">
  <h1>Gwyneth Herbert</h1>
</div>
    <%= yield %>

</body>
</html>