bandsite/config/routes.rb
Bandsite::Application.routes.draw do

  # mount Rich::Engine => '/rich', :as => 'rich'

  devise_for :users
  devise_for :fans


  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root to: "home#home"
  
  resources :posts do 
    get 'page/:page', action: :index, on: :collection
    get :photo, on: :member
    resources :post_comments
  end

  resources :tracks do
    get :song, on: :member
    resources :track_comments
  end

  resources :albums do
    get :photo, on: :member
  end

  resources :fans do
    resources :fan_comments
  end

  resources :friends do
    get :photo, on: :member
  end

  resources :reviews do
    get :photo, on: :member
    resources :review_comments
  end

  get 'reviews', to: 'reviews#index'
  get 'gigs', to: 'gigs#index'
  get 'friends', to: 'friends#index'
  get 'treasure_chest', to: 'fans#index'
  get 'contacts', to: 'contacts#index'
  get 'photogallery', to: 'photogallerys#index'

  resources :comments
end

bandsite/app/models/fan.rb
class Fan
  include Mongoid::Document
   include Mongoid::Timestamps
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :validatable, :confirmable

  # :rememberable, :trackable,

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :documents_attributes, :comments_attributes, :name
  # :remember_me

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  # field :remember_created_at, :type => Time

  ## Trackable
  # field :sign_in_count,      :type => Integer, :default => 0
  # field :current_sign_in_at, :type => Time
  # field :last_sign_in_at,    :type => Time
  # field :current_sign_in_ip, :type => String
  # field :last_sign_in_ip,    :type => String

  ## Confirmable
  field :confirmation_token,   :type => String
  field :confirmed_at,         :type => Time
  field :confirmation_sent_at, :type => Time
  field :unconfirmed_email,    :type => String

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
  field :email, type: String
  field :password, type: String
  field :role, type: String
  field :name, type: String
  ROLES = ["standard", "premium", "turbo", "mega", "daddy"]
  has_and_belongs_to_many :documents
  accepts_nested_attributes_for :documents

  # validates_associated :documents

  has_many :comments, class_name: "FanComment"
  accepts_nested_attributes_for :comments
  validates_associated :comments


  before_validation :set_default_role


  def password_required? 
    false 
  end 


private
def set_default_role
  self.role ||= "standard"
end





end

bandsite/app/controllers/fans_controller.rb
class FansController < ApplicationController

before_filter :authenticate_fan!


  def index
    @documents = Document.all
    @fans = Fan.all
    @comments = FanComment.all
    @comment = FanComment.new 
  end

  protected

  def after_sign_in_path_for(resource) 
    redirect_to fans_path
  end

end

bandsite/app/views/fans/index.html.erb
<div class="header-text">
  <h2>Welcome to the Treasure Chest</h2>
</div>
<div class="container">
  <div class="span9">
      <div class="span5">
        <h4 id="treasure-header">Drop me a message in the box below: </h4>
          <%= form_for [ current_fan, @comment ],  :remote => true do |f| %>
          <%= f.hidden_field :fan_id, value: current_fan.id %>
            <p class="blog-footer"><%= f.text_field :content, :placeholder => "Leave your message here - hit return to submit" %></p>
            <div class="invisiblebtn"><%= f.submit %></div>

            <% end %>
            <div id="fan_comments"><% @comments.each do |comment| %>
                <h5 class="chat"><%= comment.content %></h5>
              <% end %> </div>  
      </div>
          
      <div class="span4">
        <h4 id="treasure-header">Claim Your Free Download Here:</h4>


          <% @documents.each do |document| %>

            <% unless document.live.nil? %><h5 id="treasure-header"><%= link_to "Download", document.attachment.url %> <%= document.name %> here!</h5>
                <p id="treasure-text"><%= image_tag document.photo %></p>
                <p id="treasure-text"><%= document.description %></p>
            <% end %>
          <% end %>
        
        <% current_fan.documents.each do |document| %>

          <h5 id="treasure-header"><%= link_to "Download", document.attachment.url %> <%= document.name %></h5>
          <p id="treasure-text"><%= image_tag document.photo %></p>
          <p id="treasure-text"><%= document.description %></p>
        <% end %>
        
      </div>
      
    </div>

  <div class="span3">
    <%= render 'layouts/menu' %>
  </div>
</div>